import { Sunrise, RefreshCw, X, Loader2, AlertCircle } from "lucide-react";

interface MorningBriefingProps {
  content: string | null;
  loading: boolean;
  error: string | null;
  generatedAt: string | null;
  generationCount: number;
  onRegenerate: () => void;
  onDismiss: () => void;
  dismissed: boolean;
}

export function MorningBriefing({
  content, loading, error, generatedAt, generationCount, onRegenerate, onDismiss, dismissed,
}: MorningBriefingProps) {
  if (dismissed && !loading) return null;

  const dateStr = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  const timeStr = generatedAt
    ? new Date(generatedAt).toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" })
    : null;

  return (
    <div className="rounded-lg border border-primary/20 bg-card overflow-hidden mb-3">
      {/* Left accent */}
      <div className="flex">
        <div className="w-1 bg-primary shrink-0" />
        <div className="flex-1 p-3">
          {/* Header */}
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-1.5">
              <Sunrise size={14} className="text-primary" />
              <span className="text-xs font-semibold text-foreground">Morning Briefing</span>
              <span className="text-[10px] text-muted-foreground">· {dateStr}</span>
            </div>
            <button onClick={onDismiss} className="text-muted-foreground hover:text-foreground transition-colors">
              <X size={14} />
            </button>
          </div>

          {/* Content */}
          {loading ? (
            <div className="flex items-center gap-2 py-4 justify-center">
              <Loader2 size={14} className="animate-spin text-primary" />
              <span className="text-xs text-muted-foreground">Generating your briefing…</span>
            </div>
          ) : error && !content ? (
            <div className="flex items-center gap-2 py-3">
              <AlertCircle size={13} className="text-warning shrink-0" />
              <p className="text-xs text-muted-foreground">{error}</p>
              <button onClick={onRegenerate} className="text-xs text-primary hover:text-primary/80 ml-auto shrink-0">
                Retry
              </button>
            </div>
          ) : content ? (
            <>
              <p className="text-[12px] text-foreground/90 leading-relaxed">{content}</p>

              {/* Footer */}
              <div className="flex items-center justify-between mt-3 pt-2 border-t border-border/50">
                <div className="flex items-center gap-2">
                  <span className="text-[9px] text-muted-foreground/60 italic">Generated by AI — not financial advice</span>
                  {timeStr && <span className="text-[9px] text-muted-foreground/40">· {timeStr}</span>}
                </div>
                <button
                  onClick={onRegenerate}
                  disabled={loading || generationCount >= 3}
                  className="flex items-center gap-1 text-[10px] text-muted-foreground hover:text-primary transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
                  title={generationCount >= 3 ? "Max 3 regenerations per day" : "Generate a fresh briefing"}
                >
                  <RefreshCw size={10} />
                  {generationCount >= 3 ? "3/3" : `Regenerate (${generationCount}/3)`}
                </button>
              </div>
              {error && <p className="text-[10px] text-warning mt-1">{error}</p>}
            </>
          ) : null}
        </div>
      </div>
    </div>
  );
}
